# Generated by Django 4.2.8 on 2023-12-16 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(max_length=20, unique=True)),
                ("project_name", models.CharField(max_length=50)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, default=None, null=True)),
                ("expected_revenue", models.FloatField()),
            ],
        ),
    ]
