# Generated by Django 4.2.8 on 2024-01-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_project_expected_revenue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="fk_company_name",
            new_name="fk_company_id",
        ),
    ]
