# Generated by Django 4.2.8 on 2024-03-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_rename_fk_company_name_project_fk_company_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTargetRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "revenue_target",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                (
                    "fk_project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
