# Generated by Django 4.2.8 on 2024-03-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_projecttargetrevenue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_name", models.CharField(max_length=100)),
                ("pic_name", models.CharField(max_length=100)),
                ("phase_start_date", models.DateField()),
                ("phase_end_date", models.DateField(blank=True, null=True)),
                (
                    "phase_status",
                    models.CharField(
                        choices=[
                            ("pre_tender", "Pre-Tender"),
                            ("construction", "Construction"),
                            ("on_hold", "On Hold"),
                            ("final_fee_to_collect", "Final Fee to Collect"),
                            ("completed", "Completed"),
                        ]
                    ),
                ),
                ("phase_progress", models.IntegerField()),
                ("phase_fee", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "phase_additional_fee",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                ("on_hold_fee", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "cancellation_fee",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectPhaseForecastRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "fk_project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projectphase",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="project",
            old_name="expected_revenue",
            new_name="original_project_fee",
        ),
        migrations.AddField(
            model_name="project",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ProjectTargetRevenue",
        ),
        migrations.AddField(
            model_name="projectphase",
            name="fk_project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.project"
            ),
        ),
    ]
