# Generated by Django 4.2.8 on 2024-03-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_projectphase_projectphaseforecastrevenue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectphaseforecastrevenue",
            old_name="fk_project_id",
            new_name="fk_project_phase_id",
        ),
    ]
