# Generated by Django 4.2.8 on 2024-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0008_rename_fk_project_id_projectphaseforecastrevenue_fk_project_phase_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectphase",
            name="phase_progress",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectphase",
            name="phase_status",
            field=models.CharField(
                choices=[
                    ("pre_tender", "Pre-Tender"),
                    ("construction", "Construction"),
                    ("on_hold", "On Hold"),
                    ("adhoc", "Ad-hoc"),
                    ("final_fee_to_collect", "Final Fee to Collect"),
                    ("completed", "Completed"),
                ]
            ),
        ),
    ]
