# Generated by Django 4.2.8 on 2024-03-22 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_alter_projectphase_phase_progress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectphaseforecastrevenue",
            name="month",
        ),
        migrations.RemoveField(
            model_name="projectphaseforecastrevenue",
            name="year",
        ),
        migrations.AddField(
            model_name="projectphaseforecastrevenue",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="projectphase",
            name="fk_project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="project.project"
            ),
        ),
        migrations.AlterField(
            model_name="projectphaseforecastrevenue",
            name="fk_project_phase_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="project.projectphase",
            ),
        ),
    ]
