# Generated by Django 4.2.8 on 2024-03-23 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0013_alter_employee_fk_department_id_and_more"),
        ("project", "0010_remove_projectphaseforecastrevenue_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="fk_project_manager_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="employee.employee",
            ),
            preserve_default=False,
        ),
    ]
