name: timesheet_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - polars
  - protobuf
  - pendulum
  - six
  - pip
  - pip:
      - Django==4.2.8
      - django-phonenumber-field==7.2.0
      - django-slick-reporting==1.3.0
      - gspread==6.2.0
      - gspread-dataframe==3.3.1
      - phonenumbers==8.13.27
      - PyDrive==1.3.1
      - django-widget-tweaks==1.5.0
      - django-filter==25.1
      - psycopg2-binary==2.9.10
      - Babel==2.14.0
