# Generated by Django 4.2.8 on 2024-03-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="pic_contact",
            new_name="contact",
        ),
        migrations.RemoveField(
            model_name="company",
            name="pic_name",
        ),
    ]
