# Generated by Django 4.2.8 on 2024-03-22 14:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_rename_pic_contact_company_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="pic_email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
