# Generated by Django 4.2.8 on 2024-03-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0002_rename_title_position_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="department",
        ),
    ]
