# Generated by Django 4.2.8 on 2024-01-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0002_project_fk_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_no", models.CharField(max_length=100)),
                ("invoice_date", models.DateField()),
                ("amount", models.FloatField(default=0)),
                (
                    "fk_project_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("fk_project_id", "invoice_no")},
            },
        ),
    ]
