# Generated by Django 4.2.8 on 2024-01-06 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_project_expected_revenue"),
        ("project_income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectincome",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name="projectincome",
            name="fk_project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="project.project"
            ),
        ),
    ]
