# Generated by Django 4.2.8 on 2024-01-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_income", "0003_projectincomeuploadfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectincomeuploadfile",
            name="uploaded_at",
        ),
    ]
