# Generated by Django 4.2.8 on 2024-01-06 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("project_income", "0004_remove_projectincomeuploadfile_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectincomeuploadfile",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
