# Generated by Django 4.2.8 on 2024-01-06 10:32

from django.db import migrations, models
import project_income.models


class Migration(migrations.Migration):

    dependencies = [
        ("project_income", "0005_projectincomeuploadfile_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectincomeuploadfile",
            name="file",
            field=models.FileField(
                upload_to="uploads/project_income/",
                validators=[project_income.models.validate_file_extension],
            ),
        ),
    ]
