# Generated by Django 4.2.8 on 2024-03-17 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project_income.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0008_rename_fk_project_id_projectphaseforecastrevenue_fk_project_phase_id",
        ),
        ("project_income", "0006_alter_projectincomeuploadfile_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_no", models.CharField(max_length=100)),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "is_cancelled",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], default="no"
                    ),
                ),
                (
                    "fk_project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("fk_project_id", "invoice_no")},
            },
        ),
        migrations.CreateModel(
            name="ProjectInvoiceUploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/project_invoice/",
                        validators=[project_income.models.validate_file_extension],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_no", models.CharField(max_length=20, unique=True)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "fk_invoice_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_income.projectinvoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectPaymentUploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/project_payment/",
                        validators=[project_income.models.validate_file_extension],
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="projectincome",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectincome",
            name="fk_project_id",
        ),
        migrations.DeleteModel(
            name="ProjectIncomeUploadFile",
        ),
        migrations.DeleteModel(
            name="ProjectIncome",
        ),
    ]
