# Generated by Django 4.2.8 on 2023-12-11 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
