# Generated by Django 4.2.8 on 2023-12-16 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0001_initial"),
        ("employee", "0003_alter_employee_end_date_alter_employee_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="fk_position_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="position.position",
            ),
        ),
    ]
