# Generated by Django 4.2.8 on 2024-01-06 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0001_initial"),
        ("employee", "0005_alter_employee_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="fk_position_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="position.position"
            ),
        ),
    ]
