# Generated by Django 4.2.8 on 2024-03-16 03:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0002_rename_title_position_position"),
        ("employee", "0008_alter_employee_fk_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="employee_id",
            new_name="employee_code",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="first_name",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="no_of_annual_leave",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="no_of_medical_leave",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="staff_id",
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="fk_position_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="position.position"
            ),
        ),
        migrations.CreateModel(
            name="SalaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_review_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "salary_review",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                (
                    "travel_allowance",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                ("insurance", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "fk_staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
        ),
    ]
