# Generated by Django 4.2.8 on 2024-03-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_rename_employee_id_employee_employee_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salaryrecord",
            old_name="salary_review",
            new_name="salary",
        ),
    ]
