# Generated by Django 4.2.8 on 2024-03-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_rename_salary_review_salaryrecord_salary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salaryrecord",
            old_name="fk_staff_id",
            new_name="fk_employee_id",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="no_of_annual_leave",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="no_of_medical_leave",
        ),
        migrations.AddField(
            model_name="salaryrecord",
            name="no_of_annual_leave",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="salaryrecord",
            name="no_of_medical_leave",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
