# Generated by Django 4.2.8 on 2024-03-16 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0011_rename_fk_staff_id_salaryrecord_fk_employee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="fk_department_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.department",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="fk_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="staff_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
