# Generated by Django 4.2.8 on 2024-03-22 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("department", "0001_initial"),
        ("position", "0004_alter_position_position"),
        (
            "employee",
            "0012_employee_fk_department_id_alter_employee_fk_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="fk_department_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="department.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="fk_position_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="position.position"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="fk_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="salaryrecord",
            name="fk_employee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="employee.employee"
            ),
        ),
    ]
