# Generated by Django 4.2.8 on 2023-12-17 09:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_alter_employee_gender"),
        ("project", "0001_initial"),
        ("timesheet_log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetlog",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="timesheetlog",
            name="duration",
            field= models.DecimalField(max_digits=100, decimal_places=2),
        ),
        migrations.AddField(
            model_name="timesheetlog",
            name="fk_employee_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="timesheetlog",
            name="fk_project_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="project.project",
            ),
        ),
    ]
