# Generated by Django 4.2.8 on 2024-01-07 11:08

from django.db import migrations, models
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_alter_employee_fk_position_id"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollUploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/payroll_income/",
                        validators=[payroll.models.validate_file_extension],
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="payroll",
            unique_together={("fk_employee_id", "date")},
        ),
    ]
